version: "3.8"

services:
  robot-insprill:
    build: .
    container_name: robot-insprill
    restart: always
    environment:
      DISCORD_TOKEN: token
      PASTEBIN_KEY: key # Only set this if you're uploading to pastebin
#      DEV_GUILD_ID: 000000000000000000 # Uncomment to enable dev mode for the provided guild
    volumes:
      - ./config.yml:/config.yml
