version: "3.8"

services:
  robot-insprill:
    build: .
    container_name: robot-insprill
    restart: always
    environment:
      DISCORD_TOKEN: token # The token used to log in to the bot
      PASTEBIN_KEY: key # This only needs to be set if you're uploading to pastebin
    volumes:
      - ./config.yml:/config.yml
